# Generated by Django 2.2.13 on 2020-06-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('complexity', models.IntegerField(choices=[(1, 'low'), (2, 'normal'), (3, 'high')])),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number_in_course', models.IntegerField()),
                ('course_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycourse.Teacher')),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycourse.Course')),
            ],
        ),
    ]
