# Generated by Django 2.1.7 on 2020-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0002_auto_20200614_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('courses', models.ManyToManyField(to='mycourse.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course_teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course_title',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(to='mycourse.Course'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
